---
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
vectorExample <- c("小明","小英","大雄") #1,2,3

# 有多少位置可選：
length(vectorExample)
```

```{r}
vectorExample[[1]]
vectorExample[[3]]
```

```{r}
listExample <- 
  list(
    student="小明",
    `學期`=list(
      `108-1`=list(
        list(
          name="個體經濟學",
          teacher="Alice",
          grade=85
        )
      ),
      `108-2`=list(
        list(
          name="總體經濟學",
          teacher="Mark",
          grade=78
        )
      )
    )
  )
# 有多少位置可選：
length(listExample)
```

```{r}
listExample[[1]]
listExample[[2]]
```


```{r}
library(jsonlite)
fromJSON("https://data.tainan.gov.tw/dataset/4cd9345a-04bf-4328-a97d-314ff78b4763/resource/afc025fc-1ef4-447c-b785-a680391d0ca1/download/tnsport2.json", simplifyDataFrame = F) -> tainanSportsMap

length(tainanSportsMap)
```

```{r}
tainanSportsMap[[1]]
tainanSportsMap[[1076]]
    
```

```{r}
listExample$student
listExample$`學期` # 特殊命名依然要用反頓點呼叫
```

```{r}
str(listExample)
```

```{r}
str(listExample$`學期`)
```

```{r}
fromJSON("http://data.ntpc.gov.tw/api/v1/rest/datastore/382000000A-000157-002",
         simplifyDataFrame = F) -> newTaipeiCityVaccine
```

```{r}
str(newTaipeiCityVaccine)
length(newTaipeiCityVaccine)
names(newTaipeiCityVaccine)
```

```{r}
str(newTaipeiCityVaccine[[1]])
str(newTaipeiCityVaccine$success)
str(newTaipeiCityVaccine[["success"]])

str(newTaipeiCityVaccine[[2]],max.level=1)
str(newTaipeiCityVaccine$result,max.level = 1)
str(newTaipeiCityVaccine[["result"]],max.level = 1)

```

```{r}
# 顯示到第一層
str(listExample, max.level=1)

listExample[c(1,2)]
listExample[c(2,1)]
```
```{r}
str(tainanSportsMap[c(1,382,1076)],max.level =1)
```

```{r}
str(listExample, max.level = 1)

listExample[c("學期")]
listExample[c("student","學期")]
```

```{r}
fromJSON("https://www.dropbox.com/s/qnm9bnz7vccrvcz/taipeiNightMarkets.json?dl=1", simplifyDataFrame = F) -> taipeiNightMarkets
```

```{r}
str(listExample[c(F,T)]) # 不要，要
str(listExample[c(T,T)]) # 要，要
```

```{r}
names(taipeiNightMarkets)
```

```{r}
c(T,F,
  F,F,
  T,F,
  F,F,
  F,T,
  F,F,
  F,T) -> selectedMarkets
taipeiNightMarkets[selectedMarkets
                   ]
str(taipeiNightMarkets[c(T,F,
  F,F,
  T,F,
  F,F,
  F,T,
  F,F,
  F,T),],max.level = 1)
```

```{r}
selectedMarkets <- rep(F,14)#repeat F 14 times
print(selectedMarkets)
selectedMarkets[c(1,5,10,14)] <-TRUE
print(selectedMarkets)
```

```{r}
str(listExample)
```

```{r}
get1 <- listExample[["學期"]]
get2 <- listExample["學期"]

```
```{r}
str(get1,max.level = 1)
```


